### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by afarhangi** [bfaure/Python3_Data_Structures#1]
Your linked_list.lenght has a bug for list of size 1. Also, your get calls length which does an extra O(n) iteration just to check if index is valid.

**Comment by bfaure** [comment]
What is the bug for a list of size 1? I have tested inserting a single element and calling the .length() function and it returns 1 as it should.

The assertion calls to .length() in .get and .erase are certainly inefficient but I hesitate to remove them because I would like to keep the code as similar to that taught in the video as possible. That being said, removing them won't cause any issues as long as the edge cases they protect against are caught inside the while loops.

Thanks for the input!

**Comment by mdhussain7** [comment]
```
a = linked_list()
a.append(1)
a.append(2)
a.append(3)
a.append(4)
a.aapend(5)
a.append(6)

a.display()
a.remove(1)
a.display()  
```

after the code

I got This error

```
> Traceback (most recent call last):
>   File "SinglyLinkedList.py", line 59, in <module>
>     a = LinkedList()
>   File "SinglyLinkedList.py", line 8, in __init__
>     self.head = node()
> TypeError: __init__() missing 1 required positional argument: 'data'
```
Can you help me with it?

**Comment by uncleSlayer** [comment]
self.head=node()
